Project SOL_Question_Database {
  database_type: 'MongoDB'
  Note: '''
    # SOL Database
    The data come from the Virginia Department of Education (VDOE) SOL test preparation resources. 
  '''
}
Table Questions as Q {
  question_number varchar [pk]
  grade_level int [pk]
  standard varchar
  answer varchar
  question_type varchar
  note: "Data specific to each question."
}
Table Question_images as I {
  question_number varchar [pk]
  grade_level int [pk]
  image pdf
  note: "Data specific to each image."
}

Ref: Q.grade_level - I.grade_level
Ref: Q.question_number - I.question_number